name: Py4Eng
channels:
  - conda-forge
  - yoavram
  - defaults
dependencies:
  - absl-py=0.1.10=py_0
  - appnope=0.1.0=py36_0
  - asn1crypto=0.24.0=py36_0
  - backcall=0.1.0=py_0
  - backports=1.0=py36_1
  - backports.weakref=1.0rc1=py36_1
  - blas=1.1=openblas
  - bleach=1.5.0=py36_0
  - ca-certificates=2018.1.18=0
  - cartopy=0.16.0=py36_0
  - certifi=2018.1.18=py36_0
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36_0
  - clangdev=6.0.0=default_0
  - click=6.7=py_1
  - cryptography=2.2.1=py36_0
  - cycler=0.10.0=py36_0
  - cython=0.28.1=py36_0
  - dask-core=0.17.2=py_0
  - decorator=4.2.1=py36_0
  - entrypoints=0.2.3=py36_1
  - fastcache=1.0.2=py36_0
  - flask=0.12.2=py36_0
  - freetype=2.8.1=0
  - geos=3.6.2=1
  - gmp=6.1.2=0
  - gmpy2=2.0.8=py36_1
  - html5lib=0.9999999=py36_0
  - icu=58.2=0
  - idna=2.6=py36_1
  - imageio=2.3.0=py36_0
  - ipdb=0.11=py36_0
  - ipykernel=4.8.2=py36_0
  - ipython=6.3.1=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.2.0=py36_0
  - itsdangerous=0.24=py_2
  - jedi=0.11.1=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=2
  - jsonschema=2.6.0=py36_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.0.1=py36_1
  - libcxx=6.0.0=0
  - libffi=3.2.1=3
  - libgfortran=3.0.0=0
  - libiconv=1.15=0
  - libpng=1.6.34=0
  - libprotobuf=3.5.2=0
  - libsodium=1.0.16=0
  - libtiff=4.0.9=0
  - libxml2=2.9.8=0
  - libxslt=1.1.32=0
  - llvm-meta=6.0.0=0
  - llvmdev=6.0.0=default_0
  - lxml=4.2.1=py36_0
  - markdown=2.6.11=py_0
  - markupsafe=1.0=py36_0
  - matplotlib=2.2.2=py36_1
  - mistune=0.8.3=py_0
  - mpc=1.0.3=4
  - mpfr=3.1.5=0
  - mpmath=1.0.0=py_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - ncurses=5.9=10
  - networkx=2.1=py36_0
  - notebook=5.4.1=py36_0
  - numpy=1.14.2=py36_blas_openblas_200
  - olefile=0.45.1=py36_0
  - openblas=0.2.20=7
  - openssl=1.0.2n=0
  - owslib=0.16.0=py_0
  - pandas=0.22.0=py36_0
  - pandoc=2.1.3=0
  - pandocfilters=1.4.1=py36_0
  - parso=0.1.1=py_0
  - patsy=0.5.0=py36_0
  - pexpect=4.4.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pillow=5.1.0=py36_0
  - pip=9.0.3=py36_0
  - proj4=4.9.3=5
  - prompt_toolkit=1.0.15=py36_0
  - protobuf=3.5.2=py36_0
  - ptyprocess=0.5.2=py36_0
  - pycparser=2.18=py36_0
  - pyepsg=0.3.2=py36_0
  - pygments=2.2.0=py36_0
  - pyopenssl=17.5.0=py36_1
  - pyparsing=2.2.0=py36_0
  - pyproj=1.9.5.1=py36_0
  - pyshp=1.2.12=py_0
  - pysocks=1.6.8=py36_1
  - python=3.6.5=1
  - python-dateutil=2.7.2=py_0
  - pytz=2018.4=py_0
  - pywavelets=0.5.2=py36_1
  - pyzmq=17.0.0=py36_4
  - readline=7.0=0
  - requests=2.18.4=py36_1
  - scikit-image=0.13.1=py36_0
  - scikit-learn=0.19.1=py36_blas_openblas_201
  - scipy=1.0.1=py36_blas_openblas_200
  - seaborn=0.8.1=py36_0
  - send2trash=1.5.0=py_0
  - setuptools=39.0.1=py36_0
  - shapely=1.6.4=py36_0
  - simplegeneric=0.8.1=py36_0
  - six=1.11.0=py36_1
  - sqlite=3.20.1=2
  - statsmodels=0.8.0=py36_0
  - sympy=1.1.1=py36_0
  - tensorboard=1.5.1=py36_1
  - tensorflow=1.5.0=py36_0
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - tk=8.6.7=0
  - toolz=0.9.0=py_0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36_0
  - urllib3=1.22=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5=py36_0
  - werkzeug=0.14.1=py_0
  - wheel=0.31.0=py36_0
  - widgetsnbextension=3.2.0=py36_0
  - xz=5.2.3=0
  - zeromq=4.2.5=1
  - zlib=1.2.11=0
  - llvmlite=0.22.0=py36h35728e8_0
  - numba=0.37.0=np114py36h210bcc1_0
  - pip:
    - appdirs==1.4.3
    - dask==0.17.2
    - pygubu==0.9.8.2
    - sdeint==0.2.1
    - tensorflow-tensorboard==1.5.1
prefix: /Users/yoavram/miniconda3/envs/Py4Eng

